
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1457, 843)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_A = QtWidgets.QLabel(self.centralwidget)
        self.label_A.setGeometry(QtCore.QRect(191, 40, 91, 21))
        self.label_A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_A.setObjectName("label_A")
        self.spin_1A = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_1A.setGeometry(QtCore.QRect(178, 80, 42, 22))
        self.spin_1A.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_1A.setWrapping(False)
        self.spin_1A.setFrame(False)
        self.spin_1A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_1A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_1A.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spin_1A.setMinimum(1)
        self.spin_1A.setMaximum(5)
        self.spin_1A.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_1A.setObjectName("spin_1A")
        self.spin_2A = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_2A.setGeometry(QtCore.QRect(246, 80, 42, 22))
        self.spin_2A.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_2A.setFrame(False)
        self.spin_2A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_2A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_2A.setMinimum(1)
        self.spin_2A.setMaximum(5)
        self.spin_2A.setObjectName("spin_2A")
        self.label_xA = QtWidgets.QLabel(self.centralwidget)
        self.label_xA.setGeometry(QtCore.QRect(223, 80, 21, 16))
        self.label_xA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_xA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_xA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xA.setObjectName("label_xA")
        self.pushButton_PR1A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PR1A.setGeometry(QtCore.QRect(135, 120, 93, 28))
        self.pushButton_PR1A.setObjectName("pushButton_PR1A")
        self.pushButton_CL1A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CL1A.setGeometry(QtCore.QRect(240, 120, 93, 28))
        self.pushButton_CL1A.setObjectName("pushButton_CL1A")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 460, 401, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_1A = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_1A.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.grid_1A.setContentsMargins(0, 0, 0, 0)
        self.grid_1A.setObjectName("grid_1A")
        self.spin_14A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_14A.setFont(font)
        self.spin_14A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_14A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_14A.setMaximum(99999.99)
        self.spin_14A.setObjectName("spin_14A")
        self.grid_1A.addWidget(self.spin_14A, 0, 3, 1, 1)
        self.spin_41A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_41A.setFont(font)
        self.spin_41A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_41A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_41A.setMaximum(99999.99)
        self.spin_41A.setObjectName("spin_41A")
        self.grid_1A.addWidget(self.spin_41A, 3, 0, 1, 1)
        self.spin_12A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_12A.setFont(font)
        self.spin_12A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_12A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_12A.setMaximum(99999.99)
        self.spin_12A.setObjectName("spin_12A")
        self.grid_1A.addWidget(self.spin_12A, 0, 1, 1, 1)
        self.spin_45A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_45A.setFont(font)
        self.spin_45A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_45A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_45A.setMaximum(99999.99)
        self.spin_45A.setObjectName("spin_45A")
        self.grid_1A.addWidget(self.spin_45A, 3, 4, 1, 1)
        self.spin_15A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_15A.setFont(font)
        self.spin_15A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_15A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_15A.setMaximum(99999.99)
        self.spin_15A.setObjectName("spin_15A")
        self.grid_1A.addWidget(self.spin_15A, 0, 4, 1, 1)
        self.spin_31A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_31A.setFont(font)
        self.spin_31A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_31A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_31A.setMaximum(99999.99)
        self.spin_31A.setObjectName("spin_31A")
        self.grid_1A.addWidget(self.spin_31A, 2, 0, 1, 1)
        self.spin_43A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_43A.setFont(font)
        self.spin_43A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_43A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_43A.setMaximum(99999.99)
        self.spin_43A.setObjectName("spin_43A")
        self.grid_1A.addWidget(self.spin_43A, 3, 2, 1, 1)
        self.spin_22A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_22A.setFont(font)
        self.spin_22A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_22A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_22A.setMaximum(99999.99)
        self.spin_22A.setObjectName("spin_22A")
        self.grid_1A.addWidget(self.spin_22A, 1, 1, 1, 1)
        self.spin_23A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_23A.setFont(font)
        self.spin_23A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_23A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_23A.setMaximum(99999.99)
        self.spin_23A.setObjectName("spin_23A")
        self.grid_1A.addWidget(self.spin_23A, 1, 2, 1, 1)
        self.spin_11A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_11A.setFont(font)
        self.spin_11A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_11A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_11A.setMaximum(99999.99)
        self.spin_11A.setObjectName("spin_11A")
        self.grid_1A.addWidget(self.spin_11A, 0, 0, 1, 1)
        self.spin_35A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_35A.setFont(font)
        self.spin_35A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_35A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_35A.setMaximum(99999.99)
        self.spin_35A.setObjectName("spin_35A")
        self.grid_1A.addWidget(self.spin_35A, 2, 4, 1, 1)
        self.spin_13A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_13A.setFont(font)
        self.spin_13A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_13A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_13A.setMaximum(99999.99)
        self.spin_13A.setObjectName("spin_13A")
        self.grid_1A.addWidget(self.spin_13A, 0, 2, 1, 1)
        self.spin_25A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_25A.setFont(font)
        self.spin_25A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_25A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_25A.setMaximum(99999.99)
        self.spin_25A.setObjectName("spin_25A")
        self.grid_1A.addWidget(self.spin_25A, 1, 4, 1, 1)
        self.spin_44A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_44A.setFont(font)
        self.spin_44A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_44A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_44A.setMaximum(99999.99)
        self.spin_44A.setObjectName("spin_44A")
        self.grid_1A.addWidget(self.spin_44A, 3, 3, 1, 1)
        self.spin_42A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_42A.setFont(font)
        self.spin_42A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_42A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_42A.setMaximum(99999.99)
        self.spin_42A.setObjectName("spin_42A")
        self.grid_1A.addWidget(self.spin_42A, 3, 1, 1, 1)
        self.spin_21A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_21A.setFont(font)
        self.spin_21A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_21A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_21A.setMaximum(99999.99)
        self.spin_21A.setObjectName("spin_21A")
        self.grid_1A.addWidget(self.spin_21A, 1, 0, 1, 1)
        self.spin_32A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_32A.setFont(font)
        self.spin_32A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_32A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_32A.setMaximum(99999.99)
        self.spin_32A.setObjectName("spin_32A")
        self.grid_1A.addWidget(self.spin_32A, 2, 1, 1, 1)
        self.spin_33A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_33A.setFont(font)
        self.spin_33A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_33A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_33A.setMaximum(99999.99)
        self.spin_33A.setObjectName("spin_33A")
        self.grid_1A.addWidget(self.spin_33A, 2, 2, 1, 1)
        self.spin_34A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_34A.setFont(font)
        self.spin_34A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_34A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_34A.setMaximum(99999.99)
        self.spin_34A.setObjectName("spin_34A")
        self.grid_1A.addWidget(self.spin_34A, 2, 3, 1, 1)
        self.spin_24A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_24A.setFont(font)
        self.spin_24A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_24A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_24A.setMaximum(99999.99)
        self.spin_24A.setObjectName("spin_24A")
        self.grid_1A.addWidget(self.spin_24A, 1, 3, 1, 1)
        self.spin_51A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_51A.setFont(font)
        self.spin_51A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_51A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_51A.setMaximum(99999.99)
        self.spin_51A.setObjectName("spin_51A")
        self.grid_1A.addWidget(self.spin_51A, 4, 0, 1, 1)
        self.spin_52A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_52A.setFont(font)
        self.spin_52A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_52A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_52A.setMaximum(99999.99)
        self.spin_52A.setObjectName("spin_52A")
        self.grid_1A.addWidget(self.spin_52A, 4, 1, 1, 1)
        self.spin_53A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_53A.setFont(font)
        self.spin_53A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_53A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_53A.setMaximum(99999.99)
        self.spin_53A.setObjectName("spin_53A")
        self.grid_1A.addWidget(self.spin_53A, 4, 2, 1, 1)
        self.spin_54A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_54A.setFont(font)
        self.spin_54A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_54A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_54A.setMaximum(99999.99)
        self.spin_54A.setObjectName("spin_54A")
        self.grid_1A.addWidget(self.spin_54A, 4, 3, 1, 1)
        self.spin_55A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_55A.setFont(font)
        self.spin_55A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_55A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_55A.setMaximum(99999.99)
        self.spin_55A.setObjectName("spin_55A")
        self.grid_1A.addWidget(self.spin_55A, 4, 4, 1, 1)
        self.label_rA = QtWidgets.QLabel(self.centralwidget)
        self.label_rA.setGeometry(QtCore.QRect(30, 438, 401, 20))
        self.label_rA.setText("")
        self.label_rA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rA.setObjectName("label_rA")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(440, 210, 81, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.box_op = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.box_op.setContentsMargins(0, 0, 0, 0)
        self.box_op.setObjectName("box_op")
        self.pushButton_s0 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_s0.setObjectName("pushButton_s0")
        self.box_op.addWidget(self.pushButton_s0)
        self.pushButton_s1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_s1.setObjectName("pushButton_s1")
        self.box_op.addWidget(self.pushButton_s1)
        self.pushButton_s2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_s2.setObjectName("pushButton_s2")
        self.box_op.addWidget(self.pushButton_s2)
        self.pushButton_s3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_s3.setObjectName("pushButton_s3")
        self.box_op.addWidget(self.pushButton_s3)
        self.spin_2B = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_2B.setGeometry(QtCore.QRect(741, 80, 42, 22))
        self.spin_2B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_2B.setFrame(False)
        self.spin_2B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_2B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_2B.setMinimum(1)
        self.spin_2B.setMaximum(5)
        self.spin_2B.setObjectName("spin_2B")
        self.label_B = QtWidgets.QLabel(self.centralwidget)
        self.label_B.setGeometry(QtCore.QRect(683, 40, 91, 21))
        self.label_B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_B.setObjectName("label_B")
        self.label_xA_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_xA_2.setGeometry(QtCore.QRect(718, 80, 21, 16))
        self.label_xA_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_xA_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_xA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xA_2.setObjectName("label_xA_2")
        self.pushButton_PR1B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PR1B.setGeometry(QtCore.QRect(630, 120, 93, 28))
        self.pushButton_PR1B.setObjectName("pushButton_PR1B")
        self.label_rB = QtWidgets.QLabel(self.centralwidget)
        self.label_rB.setGeometry(QtCore.QRect(530, 438, 391, 20))
        self.label_rB.setText("")
        self.label_rB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rB.setObjectName("label_rB")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(530, 460, 401, 161))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.grid_1B = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.grid_1B.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.grid_1B.setContentsMargins(0, 0, 0, 0)
        self.grid_1B.setObjectName("grid_1B")
        self.spin_54B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_54B.setFont(font)
        self.spin_54B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_54B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_54B.setMaximum(99999.99)
        self.spin_54B.setObjectName("spin_54B")
        self.grid_1B.addWidget(self.spin_54B, 4, 3, 1, 1)
        self.spin_41B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_41B.setFont(font)
        self.spin_41B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_41B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_41B.setMaximum(99999.99)
        self.spin_41B.setObjectName("spin_41B")
        self.grid_1B.addWidget(self.spin_41B, 3, 0, 1, 1)
        self.spin_21B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_21B.setFont(font)
        self.spin_21B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_21B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_21B.setMaximum(99999.99)
        self.spin_21B.setObjectName("spin_21B")
        self.grid_1B.addWidget(self.spin_21B, 1, 0, 1, 1)
        self.spin_25B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_25B.setFont(font)
        self.spin_25B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_25B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_25B.setMaximum(99999.99)
        self.spin_25B.setObjectName("spin_25B")
        self.grid_1B.addWidget(self.spin_25B, 1, 4, 1, 1)
        self.spin_35B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_35B.setFont(font)
        self.spin_35B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_35B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_35B.setMaximum(99999.99)
        self.spin_35B.setObjectName("spin_35B")
        self.grid_1B.addWidget(self.spin_35B, 2, 4, 1, 1)
        self.spin_34B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_34B.setFont(font)
        self.spin_34B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_34B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_34B.setMaximum(99999.99)
        self.spin_34B.setObjectName("spin_34B")
        self.grid_1B.addWidget(self.spin_34B, 2, 3, 1, 1)
        self.spin_53B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_53B.setFont(font)
        self.spin_53B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_53B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_53B.setMaximum(99999.99)
        self.spin_53B.setObjectName("spin_53B")
        self.grid_1B.addWidget(self.spin_53B, 4, 2, 1, 1)
        self.spin_15B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_15B.setFont(font)
        self.spin_15B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_15B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_15B.setMaximum(99999.99)
        self.spin_15B.setObjectName("spin_15B")
        self.grid_1B.addWidget(self.spin_15B, 0, 4, 1, 1)
        self.spin_32B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_32B.setFont(font)
        self.spin_32B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_32B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_32B.setMaximum(99999.99)
        self.spin_32B.setObjectName("spin_32B")
        self.grid_1B.addWidget(self.spin_32B, 2, 1, 1, 1)
        self.spin_44B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_44B.setFont(font)
        self.spin_44B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_44B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_44B.setMaximum(99999.99)
        self.spin_44B.setObjectName("spin_44B")
        self.grid_1B.addWidget(self.spin_44B, 3, 3, 1, 1)
        self.spin_45B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_45B.setFont(font)
        self.spin_45B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_45B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_45B.setMaximum(99999.99)
        self.spin_45B.setObjectName("spin_45B")
        self.grid_1B.addWidget(self.spin_45B, 3, 4, 1, 1)
        self.spin_22B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_22B.setFont(font)
        self.spin_22B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_22B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_22B.setMaximum(99999.99)
        self.spin_22B.setObjectName("spin_22B")
        self.grid_1B.addWidget(self.spin_22B, 1, 1, 1, 1)
        self.spin_31B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_31B.setFont(font)
        self.spin_31B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_31B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_31B.setMaximum(99999.99)
        self.spin_31B.setObjectName("spin_31B")
        self.grid_1B.addWidget(self.spin_31B, 2, 0, 1, 1)
        self.spin_23B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_23B.setFont(font)
        self.spin_23B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_23B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_23B.setMaximum(99999.99)
        self.spin_23B.setObjectName("spin_23B")
        self.grid_1B.addWidget(self.spin_23B, 1, 2, 1, 1)
        self.spin_33B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_33B.setFont(font)
        self.spin_33B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_33B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_33B.setMaximum(99999.99)
        self.spin_33B.setObjectName("spin_33B")
        self.grid_1B.addWidget(self.spin_33B, 2, 2, 1, 1)
        self.spin_11B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_11B.setFont(font)
        self.spin_11B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_11B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_11B.setMaximum(99999.99)
        self.spin_11B.setObjectName("spin_11B")
        self.grid_1B.addWidget(self.spin_11B, 0, 0, 1, 1)
        self.spin_52B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_52B.setFont(font)
        self.spin_52B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_52B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_52B.setMaximum(99999.99)
        self.spin_52B.setObjectName("spin_52B")
        self.grid_1B.addWidget(self.spin_52B, 4, 1, 1, 1)
        self.spin_42B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_42B.setFont(font)
        self.spin_42B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_42B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_42B.setMaximum(99999.99)
        self.spin_42B.setObjectName("spin_42B")
        self.grid_1B.addWidget(self.spin_42B, 3, 1, 1, 1)
        self.spin_55B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_55B.setFont(font)
        self.spin_55B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_55B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_55B.setMaximum(99999.99)
        self.spin_55B.setObjectName("spin_55B")
        self.grid_1B.addWidget(self.spin_55B, 4, 4, 1, 1)
        self.spin_14B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_14B.setFont(font)
        self.spin_14B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_14B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_14B.setMaximum(99999.99)
        self.spin_14B.setObjectName("spin_14B")
        self.grid_1B.addWidget(self.spin_14B, 0, 3, 1, 1)
        self.spin_12B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_12B.setFont(font)
        self.spin_12B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_12B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_12B.setMaximum(99999.99)
        self.spin_12B.setObjectName("spin_12B")
        self.grid_1B.addWidget(self.spin_12B, 0, 1, 1, 1)
        self.spin_51B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_51B.setFont(font)
        self.spin_51B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_51B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_51B.setMaximum(99999.99)
        self.spin_51B.setObjectName("spin_51B")
        self.grid_1B.addWidget(self.spin_51B, 4, 0, 1, 1)
        self.spin_13B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_13B.setFont(font)
        self.spin_13B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_13B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_13B.setMaximum(99999.99)
        self.spin_13B.setObjectName("spin_13B")
        self.grid_1B.addWidget(self.spin_13B, 0, 2, 1, 1)
        self.spin_24B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_24B.setFont(font)
        self.spin_24B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_24B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_24B.setMaximum(99999.99)
        self.spin_24B.setObjectName("spin_24B")
        self.grid_1B.addWidget(self.spin_24B, 1, 3, 1, 1)
        self.spin_43B = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_43B.setFont(font)
        self.spin_43B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_43B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_43B.setMaximum(99999.99)
        self.spin_43B.setObjectName("spin_43B")
        self.grid_1B.addWidget(self.spin_43B, 3, 2, 1, 1)
        self.pushButton_CL1B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CL1B.setGeometry(QtCore.QRect(735, 120, 93, 28))
        self.pushButton_CL1B.setObjectName("pushButton_CL1B")
        self.spin_1B = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_1B.setGeometry(QtCore.QRect(673, 80, 42, 22))
        self.spin_1B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_1B.setWrapping(False)
        self.spin_1B.setFrame(False)
        self.spin_1B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_1B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_1B.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spin_1B.setMinimum(1)
        self.spin_1B.setMaximum(5)
        self.spin_1B.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_1B.setObjectName("spin_1B")
        self.label_xA_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_xA_3.setGeometry(QtCore.QRect(1195, 80, 21, 16))
        self.label_xA_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_xA_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_xA_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xA_3.setObjectName("label_xA_3")
        self.spin_2C = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_2C.setGeometry(QtCore.QRect(1218, 80, 42, 22))
        self.spin_2C.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_2C.setFrame(False)
        self.spin_2C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_2C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_2C.setMinimum(1)
        self.spin_2C.setMaximum(5)
        self.spin_2C.setObjectName("spin_2C")
        self.label_C = QtWidgets.QLabel(self.centralwidget)
        self.label_C.setGeometry(QtCore.QRect(1163, 40, 91, 21))
        self.label_C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_C.setObjectName("label_C")
        self.label_rC = QtWidgets.QLabel(self.centralwidget)
        self.label_rC.setGeometry(QtCore.QRect(1010, 438, 391, 20))
        self.label_rC.setText("")
        self.label_rC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rC.setObjectName("label_rC")
        self.pushButton_PR1C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PR1C.setGeometry(QtCore.QRect(1105, 120, 93, 28))
        self.pushButton_PR1C.setObjectName("pushButton_PR1C")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(1000, 460, 401, 161))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.grid_1C = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.grid_1C.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.grid_1C.setContentsMargins(0, 0, 0, 0)
        self.grid_1C.setObjectName("grid_1C")
        self.spin_54C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_54C.setFont(font)
        self.spin_54C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_54C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_54C.setMaximum(99999.99)
        self.spin_54C.setObjectName("spin_54C")
        self.grid_1C.addWidget(self.spin_54C, 4, 3, 1, 1)
        self.spin_41C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_41C.setFont(font)
        self.spin_41C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_41C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_41C.setMaximum(99999.99)
        self.spin_41C.setObjectName("spin_41C")
        self.grid_1C.addWidget(self.spin_41C, 3, 0, 1, 1)
        self.spin_21C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_21C.setFont(font)
        self.spin_21C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_21C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_21C.setMaximum(99999.99)
        self.spin_21C.setObjectName("spin_21C")
        self.grid_1C.addWidget(self.spin_21C, 1, 0, 1, 1)
        self.spin_25C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_25C.setFont(font)
        self.spin_25C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_25C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_25C.setMaximum(99999.99)
        self.spin_25C.setObjectName("spin_25C")
        self.grid_1C.addWidget(self.spin_25C, 1, 4, 1, 1)
        self.spin_35C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_35C.setFont(font)
        self.spin_35C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_35C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_35C.setMaximum(99999.99)
        self.spin_35C.setObjectName("spin_35C")
        self.grid_1C.addWidget(self.spin_35C, 2, 4, 1, 1)
        self.spin_34C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_34C.setFont(font)
        self.spin_34C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_34C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_34C.setMaximum(99999.99)
        self.spin_34C.setObjectName("spin_34C")
        self.grid_1C.addWidget(self.spin_34C, 2, 3, 1, 1)
        self.spin_53C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_53C.setFont(font)
        self.spin_53C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_53C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_53C.setMaximum(99999.99)
        self.spin_53C.setObjectName("spin_53C")
        self.grid_1C.addWidget(self.spin_53C, 4, 2, 1, 1)
        self.spin_15C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_15C.setFont(font)
        self.spin_15C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_15C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_15C.setMaximum(99999.99)
        self.spin_15C.setObjectName("spin_15C")
        self.grid_1C.addWidget(self.spin_15C, 0, 4, 1, 1)
        self.spin_32C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_32C.setFont(font)
        self.spin_32C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_32C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_32C.setMaximum(99999.99)
        self.spin_32C.setObjectName("spin_32C")
        self.grid_1C.addWidget(self.spin_32C, 2, 1, 1, 1)
        self.spin_44C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_44C.setFont(font)
        self.spin_44C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_44C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_44C.setMaximum(99999.99)
        self.spin_44C.setObjectName("spin_44C")
        self.grid_1C.addWidget(self.spin_44C, 3, 3, 1, 1)
        self.spin_45C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_45C.setFont(font)
        self.spin_45C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_45C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_45C.setMaximum(99999.99)
        self.spin_45C.setObjectName("spin_45C")
        self.grid_1C.addWidget(self.spin_45C, 3, 4, 1, 1)
        self.spin_22C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_22C.setFont(font)
        self.spin_22C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_22C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_22C.setMaximum(99999.99)
        self.spin_22C.setObjectName("spin_22C")
        self.grid_1C.addWidget(self.spin_22C, 1, 1, 1, 1)
        self.spin_31C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_31C.setFont(font)
        self.spin_31C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_31C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_31C.setMaximum(99999.99)
        self.spin_31C.setObjectName("spin_31C")
        self.grid_1C.addWidget(self.spin_31C, 2, 0, 1, 1)
        self.spin_23C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_23C.setFont(font)
        self.spin_23C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_23C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_23C.setMaximum(99999.99)
        self.spin_23C.setObjectName("spin_23C")
        self.grid_1C.addWidget(self.spin_23C, 1, 2, 1, 1)
        self.spin_33C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_33C.setFont(font)
        self.spin_33C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_33C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_33C.setMaximum(99999.99)
        self.spin_33C.setObjectName("spin_33C")
        self.grid_1C.addWidget(self.spin_33C, 2, 2, 1, 1)
        self.spin_11C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_11C.setFont(font)
        self.spin_11C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_11C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_11C.setMaximum(99999.99)
        self.spin_11C.setObjectName("spin_11C")
        self.grid_1C.addWidget(self.spin_11C, 0, 0, 1, 1)
        self.spin_52C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_52C.setFont(font)
        self.spin_52C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_52C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_52C.setMaximum(99999.99)
        self.spin_52C.setObjectName("spin_52C")
        self.grid_1C.addWidget(self.spin_52C, 4, 1, 1, 1)
        self.spin_42C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_42C.setFont(font)
        self.spin_42C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_42C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_42C.setMaximum(99999.99)
        self.spin_42C.setObjectName("spin_42C")
        self.grid_1C.addWidget(self.spin_42C, 3, 1, 1, 1)
        self.spin_55C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_55C.setFont(font)
        self.spin_55C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_55C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_55C.setMaximum(99999.99)
        self.spin_55C.setObjectName("spin_55C")
        self.grid_1C.addWidget(self.spin_55C, 4, 4, 1, 1)
        self.spin_14C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_14C.setFont(font)
        self.spin_14C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_14C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_14C.setMaximum(99999.99)
        self.spin_14C.setObjectName("spin_14C")
        self.grid_1C.addWidget(self.spin_14C, 0, 3, 1, 1)
        self.spin_12C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_12C.setFont(font)
        self.spin_12C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_12C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_12C.setMaximum(99999.99)
        self.spin_12C.setObjectName("spin_12C")
        self.grid_1C.addWidget(self.spin_12C, 0, 1, 1, 1)
        self.spin_51C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_51C.setFont(font)
        self.spin_51C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_51C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_51C.setMaximum(99999.99)
        self.spin_51C.setObjectName("spin_51C")
        self.grid_1C.addWidget(self.spin_51C, 4, 0, 1, 1)
        self.spin_13C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_13C.setFont(font)
        self.spin_13C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_13C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_13C.setMaximum(99999.99)
        self.spin_13C.setObjectName("spin_13C")
        self.grid_1C.addWidget(self.spin_13C, 0, 2, 1, 1)
        self.spin_24C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_24C.setFont(font)
        self.spin_24C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_24C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_24C.setMaximum(99999.99)
        self.spin_24C.setObjectName("spin_24C")
        self.grid_1C.addWidget(self.spin_24C, 1, 3, 1, 1)
        self.spin_43C = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spin_43C.setFont(font)
        self.spin_43C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_43C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_43C.setMaximum(99999.99)
        self.spin_43C.setObjectName("spin_43C")
        self.grid_1C.addWidget(self.spin_43C, 3, 2, 1, 1)
        self.pushButton_CL1C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CL1C.setGeometry(QtCore.QRect(1210, 120, 93, 28))
        self.pushButton_CL1C.setObjectName("pushButton_CL1C")
        self.spin_1C = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_1C.setGeometry(QtCore.QRect(1150, 80, 42, 22))
        self.spin_1C.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_1C.setWrapping(False)
        self.spin_1C.setFrame(False)
        self.spin_1C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_1C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_1C.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spin_1C.setMinimum(1)
        self.spin_1C.setMaximum(5)
        self.spin_1C.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_1C.setObjectName("spin_1C")
        self.label_rav = QtWidgets.QLabel(self.centralwidget)
        self.label_rav.setGeometry(QtCore.QRect(945, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_rav.setFont(font)
        self.label_rav.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rav.setObjectName("label_rav")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 640, 1111, 165))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 50, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_q.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_q.setFont(font)
        self.label_q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q.setObjectName("label_q")
        self.horizontalLayout.addWidget(self.label_q)
        self.grid_q = QtWidgets.QGridLayout()
        self.grid_q.setObjectName("grid_q")
        self.label_54q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_54q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_54q.setLineWidth(0)
        self.label_54q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54q.setObjectName("label_54q")
        self.grid_q.addWidget(self.label_54q, 4, 3, 1, 1)
        self.label_31q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_31q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31q.setLineWidth(0)
        self.label_31q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31q.setObjectName("label_31q")
        self.grid_q.addWidget(self.label_31q, 2, 0, 1, 1)
        self.label_34q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_34q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_34q.setLineWidth(0)
        self.label_34q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34q.setObjectName("label_34q")
        self.grid_q.addWidget(self.label_34q, 2, 3, 1, 1)
        self.label_52q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_52q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52q.setLineWidth(0)
        self.label_52q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52q.setObjectName("label_52q")
        self.grid_q.addWidget(self.label_52q, 4, 1, 1, 1)
        self.label_14q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_14q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14q.setLineWidth(0)
        self.label_14q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14q.setObjectName("label_14q")
        self.grid_q.addWidget(self.label_14q, 0, 3, 1, 1)
        self.label_44q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_44q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_44q.setLineWidth(0)
        self.label_44q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44q.setObjectName("label_44q")
        self.grid_q.addWidget(self.label_44q, 3, 3, 1, 1)
        self.label_32q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_32q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_32q.setLineWidth(0)
        self.label_32q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32q.setObjectName("label_32q")
        self.grid_q.addWidget(self.label_32q, 2, 1, 1, 1)
        self.label_51q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_51q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_51q.setLineWidth(0)
        self.label_51q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51q.setObjectName("label_51q")
        self.grid_q.addWidget(self.label_51q, 4, 0, 1, 1)
        self.label_21q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_21q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21q.setLineWidth(0)
        self.label_21q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21q.setObjectName("label_21q")
        self.grid_q.addWidget(self.label_21q, 1, 0, 1, 1)
        self.label_33q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_33q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_33q.setLineWidth(0)
        self.label_33q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33q.setObjectName("label_33q")
        self.grid_q.addWidget(self.label_33q, 2, 2, 1, 1)
        self.label_42q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_42q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_42q.setLineWidth(0)
        self.label_42q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42q.setObjectName("label_42q")
        self.grid_q.addWidget(self.label_42q, 3, 1, 1, 1)
        self.label_12q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_12q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12q.setLineWidth(0)
        self.label_12q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12q.setObjectName("label_12q")
        self.grid_q.addWidget(self.label_12q, 0, 1, 1, 1)
        self.label_22q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_22q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_22q.setLineWidth(0)
        self.label_22q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22q.setObjectName("label_22q")
        self.grid_q.addWidget(self.label_22q, 1, 1, 1, 1)
        self.label_11q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11q.setLineWidth(0)
        self.label_11q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11q.setObjectName("label_11q")
        self.grid_q.addWidget(self.label_11q, 0, 0, 1, 1)
        self.label_53q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_53q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_53q.setLineWidth(0)
        self.label_53q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53q.setObjectName("label_53q")
        self.grid_q.addWidget(self.label_53q, 4, 2, 1, 1)
        self.label_41q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_41q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_41q.setLineWidth(0)
        self.label_41q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41q.setObjectName("label_41q")
        self.grid_q.addWidget(self.label_41q, 3, 0, 1, 1)
        self.label_24q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_24q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_24q.setLineWidth(0)
        self.label_24q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24q.setObjectName("label_24q")
        self.grid_q.addWidget(self.label_24q, 1, 3, 1, 1)
        self.label_25q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_25q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_25q.setLineWidth(0)
        self.label_25q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25q.setObjectName("label_25q")
        self.grid_q.addWidget(self.label_25q, 1, 4, 1, 1)
        self.label_13q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_13q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13q.setLineWidth(0)
        self.label_13q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13q.setObjectName("label_13q")
        self.grid_q.addWidget(self.label_13q, 0, 2, 1, 1)
        self.label_43q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_43q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_43q.setLineWidth(0)
        self.label_43q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43q.setObjectName("label_43q")
        self.grid_q.addWidget(self.label_43q, 3, 2, 1, 1)
        self.label_35q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_35q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_35q.setLineWidth(0)
        self.label_35q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35q.setObjectName("label_35q")
        self.grid_q.addWidget(self.label_35q, 2, 4, 1, 1)
        self.label_45q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_45q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_45q.setLineWidth(0)
        self.label_45q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45q.setObjectName("label_45q")
        self.grid_q.addWidget(self.label_45q, 3, 4, 1, 1)
        self.label_15q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_15q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15q.setLineWidth(0)
        self.label_15q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15q.setObjectName("label_15q")
        self.grid_q.addWidget(self.label_15q, 0, 4, 1, 1)
        self.label_55q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_55q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_55q.setLineWidth(0)
        self.label_55q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55q.setObjectName("label_55q")
        self.grid_q.addWidget(self.label_55q, 4, 4, 1, 1)
        self.label_23q = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_23q.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_23q.setLineWidth(0)
        self.label_23q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23q.setObjectName("label_23q")
        self.grid_q.addWidget(self.label_23q, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.grid_q)
        self.label_r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_r.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_r.setFont(font)
        self.label_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r.setObjectName("label_r")
        self.horizontalLayout.addWidget(self.label_r)
        self.grid_r = QtWidgets.QGridLayout()
        self.grid_r.setObjectName("grid_r")
        self.label_53r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_53r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_53r.setLineWidth(0)
        self.label_53r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53r.setObjectName("label_53r")
        self.grid_r.addWidget(self.label_53r, 4, 2, 1, 1)
        self.label_12r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_12r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12r.setLineWidth(0)
        self.label_12r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12r.setObjectName("label_12r")
        self.grid_r.addWidget(self.label_12r, 0, 1, 1, 1)
        self.label_41r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_41r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_41r.setLineWidth(0)
        self.label_41r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41r.setObjectName("label_41r")
        self.grid_r.addWidget(self.label_41r, 3, 0, 1, 1)
        self.label_25r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_25r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_25r.setLineWidth(0)
        self.label_25r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25r.setObjectName("label_25r")
        self.grid_r.addWidget(self.label_25r, 1, 4, 1, 1)
        self.label_31r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_31r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31r.setLineWidth(0)
        self.label_31r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31r.setObjectName("label_31r")
        self.grid_r.addWidget(self.label_31r, 2, 0, 1, 1)
        self.label_34r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_34r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_34r.setLineWidth(0)
        self.label_34r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34r.setObjectName("label_34r")
        self.grid_r.addWidget(self.label_34r, 2, 3, 1, 1)
        self.label_22r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_22r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_22r.setLineWidth(0)
        self.label_22r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22r.setObjectName("label_22r")
        self.grid_r.addWidget(self.label_22r, 1, 1, 1, 1)
        self.label_24r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_24r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_24r.setLineWidth(0)
        self.label_24r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24r.setObjectName("label_24r")
        self.grid_r.addWidget(self.label_24r, 1, 3, 1, 1)
        self.label_35r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_35r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_35r.setLineWidth(0)
        self.label_35r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35r.setObjectName("label_35r")
        self.grid_r.addWidget(self.label_35r, 2, 4, 1, 1)
        self.label_52r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_52r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52r.setLineWidth(0)
        self.label_52r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52r.setObjectName("label_52r")
        self.grid_r.addWidget(self.label_52r, 4, 1, 1, 1)
        self.label_33r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_33r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_33r.setLineWidth(0)
        self.label_33r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33r.setObjectName("label_33r")
        self.grid_r.addWidget(self.label_33r, 2, 2, 1, 1)
        self.label_51r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_51r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_51r.setLineWidth(0)
        self.label_51r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51r.setObjectName("label_51r")
        self.grid_r.addWidget(self.label_51r, 4, 0, 1, 1)
        self.label_43r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_43r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_43r.setLineWidth(0)
        self.label_43r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43r.setObjectName("label_43r")
        self.grid_r.addWidget(self.label_43r, 3, 2, 1, 1)
        self.label_11r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11r.setLineWidth(0)
        self.label_11r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11r.setObjectName("label_11r")
        self.grid_r.addWidget(self.label_11r, 0, 0, 1, 1)
        self.label_44r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_44r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_44r.setLineWidth(0)
        self.label_44r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44r.setObjectName("label_44r")
        self.grid_r.addWidget(self.label_44r, 3, 3, 1, 1)
        self.label_15r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_15r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15r.setLineWidth(0)
        self.label_15r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15r.setObjectName("label_15r")
        self.grid_r.addWidget(self.label_15r, 0, 4, 1, 1)
        self.label_54r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_54r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_54r.setLineWidth(0)
        self.label_54r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54r.setObjectName("label_54r")
        self.grid_r.addWidget(self.label_54r, 4, 3, 1, 1)
        self.label_55r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_55r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_55r.setLineWidth(0)
        self.label_55r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55r.setObjectName("label_55r")
        self.grid_r.addWidget(self.label_55r, 4, 4, 1, 1)
        self.label_45r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_45r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_45r.setLineWidth(0)
        self.label_45r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45r.setObjectName("label_45r")
        self.grid_r.addWidget(self.label_45r, 3, 4, 1, 1)
        self.label_32r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_32r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_32r.setLineWidth(0)
        self.label_32r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32r.setObjectName("label_32r")
        self.grid_r.addWidget(self.label_32r, 2, 1, 1, 1)
        self.label_21r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_21r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21r.setLineWidth(0)
        self.label_21r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21r.setObjectName("label_21r")
        self.grid_r.addWidget(self.label_21r, 1, 0, 1, 1)
        self.label_13r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_13r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13r.setLineWidth(0)
        self.label_13r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13r.setObjectName("label_13r")
        self.grid_r.addWidget(self.label_13r, 0, 2, 1, 1)
        self.label_23r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_23r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_23r.setLineWidth(0)
        self.label_23r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23r.setObjectName("label_23r")
        self.grid_r.addWidget(self.label_23r, 1, 2, 1, 1)
        self.label_42r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_42r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_42r.setLineWidth(0)
        self.label_42r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42r.setObjectName("label_42r")
        self.grid_r.addWidget(self.label_42r, 3, 1, 1, 1)
        self.label_14r = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_14r.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14r.setLineWidth(0)
        self.label_14r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14r.setObjectName("label_14r")
        self.grid_r.addWidget(self.label_14r, 0, 3, 1, 1)
        self.horizontalLayout.addLayout(self.grid_r)
        self.spin_p1A = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p1A.setGeometry(QtCore.QRect(170, 245, 58, 28))
        self.spin_p1A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p1A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p1A.setMinimum(-999.0)
        self.spin_p1A.setMaximum(999.0)
        self.spin_p1A.setObjectName("spin_p1A")
        self.spin_p3A = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p3A.setGeometry(QtCore.QRect(170, 325, 58, 28))
        self.spin_p3A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p3A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p3A.setMinimum(-999.0)
        self.spin_p3A.setMaximum(999.0)
        self.spin_p3A.setObjectName("spin_p3A")
        self.spin_p2A = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_p2A.setGeometry(QtCore.QRect(170, 285, 58, 28))
        self.spin_p2A.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p2A.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p2A.setObjectName("spin_p2A")
        self.spin_p1B = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p1B.setGeometry(QtCore.QRect(665, 245, 58, 28))
        self.spin_p1B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p1B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p1B.setMaximum(999.0)
        self.spin_p1B.setObjectName("spin_p1B")
        self.spin_p3B = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p3B.setGeometry(QtCore.QRect(665, 325, 58, 28))
        self.spin_p3B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p3B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p3B.setMaximum(999.0)
        self.spin_p3B.setObjectName("spin_p3B")
        self.spin_p2B = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_p2B.setGeometry(QtCore.QRect(665, 285, 58, 28))
        self.spin_p2B.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p2B.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p2B.setObjectName("spin_p2B")
        self.spin_p1C = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p1C.setGeometry(QtCore.QRect(1140, 245, 59, 28))
        self.spin_p1C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p1C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p1C.setMaximum(999.0)
        self.spin_p1C.setObjectName("spin_p1C")
        self.spin_p2C = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_p2C.setGeometry(QtCore.QRect(1140, 285, 58, 28))
        self.spin_p2C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p2C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p2C.setObjectName("spin_p2C")
        self.spin_p3C = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_p3C.setGeometry(QtCore.QRect(1140, 325, 58, 28))
        self.spin_p3C.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_p3C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_p3C.setMaximum(999.0)
        self.spin_p3C.setObjectName("spin_p3C")
        self.pushButton_a1A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a1A.setGeometry(QtCore.QRect(236, 164, 200, 30))
        self.pushButton_a1A.setObjectName("pushButton_a1A")
        self.pushButton_5A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5A.setGeometry(QtCore.QRect(30, 324, 141, 30))
        self.pushButton_5A.setObjectName("pushButton_5A")
        self.pushButton_7A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7A.setGeometry(QtCore.QRect(30, 404, 201, 30))
        self.pushButton_7A.setObjectName("pushButton_7A")
        self.pushButton_a3A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a3A.setGeometry(QtCore.QRect(236, 244, 201, 30))
        self.pushButton_a3A.setObjectName("pushButton_a3A")
        self.pushButton_a6A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a6A.setGeometry(QtCore.QRect(236, 364, 201, 30))
        self.pushButton_a6A.setObjectName("pushButton_a6A")
        self.pushButton_3A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3A.setGeometry(QtCore.QRect(30, 244, 141, 30))
        self.pushButton_3A.setObjectName("pushButton_3A")
        self.pushButton_6A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6A.setGeometry(QtCore.QRect(30, 364, 201, 30))
        self.pushButton_6A.setObjectName("pushButton_6A")
        self.pushButton_a4A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a4A.setGeometry(QtCore.QRect(236, 284, 201, 30))
        self.pushButton_a4A.setObjectName("pushButton_a4A")
        self.pushButton_a5A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a5A.setGeometry(QtCore.QRect(236, 324, 201, 30))
        self.pushButton_a5A.setObjectName("pushButton_a5A")
        self.pushButton_4A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4A.setGeometry(QtCore.QRect(30, 284, 141, 30))
        self.pushButton_4A.setObjectName("pushButton_4A")
        self.pushButton_a7A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a7A.setGeometry(QtCore.QRect(236, 404, 201, 30))
        self.pushButton_a7A.setObjectName("pushButton_a7A")
        self.pushButton_a2A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a2A.setGeometry(QtCore.QRect(236, 204, 201, 30))
        self.pushButton_a2A.setObjectName("pushButton_a2A")
        self.pushButton_2A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2A.setGeometry(QtCore.QRect(30, 204, 200, 30))
        self.pushButton_2A.setObjectName("pushButton_2A")
        self.pushButton_1A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1A.setGeometry(QtCore.QRect(30, 164, 200, 30))
        self.pushButton_1A.setObjectName("pushButton_1A")
        self.pushButton_a1B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a1B.setGeometry(QtCore.QRect(733, 164, 200, 30))
        self.pushButton_a1B.setObjectName("pushButton_a1B")
        self.pushButton_5B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5B.setGeometry(QtCore.QRect(525, 324, 141, 30))
        self.pushButton_5B.setObjectName("pushButton_5B")
        self.pushButton_7B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7B.setGeometry(QtCore.QRect(525, 404, 201, 30))
        self.pushButton_7B.setObjectName("pushButton_7B")
        self.pushButton_a3B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a3B.setGeometry(QtCore.QRect(733, 244, 201, 30))
        self.pushButton_a3B.setObjectName("pushButton_a3B")
        self.pushButton_a6B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a6B.setGeometry(QtCore.QRect(733, 364, 201, 30))
        self.pushButton_a6B.setObjectName("pushButton_a6B")
        self.pushButton_3B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3B.setGeometry(QtCore.QRect(525, 244, 141, 30))
        self.pushButton_3B.setObjectName("pushButton_3B")
        self.pushButton_6B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6B.setGeometry(QtCore.QRect(525, 364, 201, 30))
        self.pushButton_6B.setObjectName("pushButton_6B")
        self.pushButton_a4B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a4B.setGeometry(QtCore.QRect(733, 284, 201, 30))
        self.pushButton_a4B.setObjectName("pushButton_a4B")
        self.pushButton_a5B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a5B.setGeometry(QtCore.QRect(733, 324, 201, 30))
        self.pushButton_a5B.setObjectName("pushButton_a5B")
        self.pushButton_4B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4B.setGeometry(QtCore.QRect(525, 284, 141, 30))
        self.pushButton_4B.setObjectName("pushButton_4B")
        self.pushButton_a7B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a7B.setGeometry(QtCore.QRect(733, 404, 201, 30))
        self.pushButton_a7B.setObjectName("pushButton_a7B")
        self.pushButton_a2B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a2B.setGeometry(QtCore.QRect(733, 204, 201, 30))
        self.pushButton_a2B.setObjectName("pushButton_a2B")
        self.pushButton_2B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2B.setGeometry(QtCore.QRect(525, 204, 201, 30))
        self.pushButton_2B.setObjectName("pushButton_2B")
        self.pushButton_1B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1B.setGeometry(QtCore.QRect(525, 164, 200, 30))
        self.pushButton_1B.setObjectName("pushButton_1B")
        self.pushButton_a1C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a1C.setGeometry(QtCore.QRect(1208, 164, 200, 30))
        self.pushButton_a1C.setObjectName("pushButton_a1C")
        self.pushButton_5C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5C.setGeometry(QtCore.QRect(1000, 324, 141, 30))
        self.pushButton_5C.setObjectName("pushButton_5C")
        self.pushButton_7C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7C.setGeometry(QtCore.QRect(1000, 404, 201, 30))
        self.pushButton_7C.setObjectName("pushButton_7C")
        self.pushButton_a3C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a3C.setGeometry(QtCore.QRect(1208, 244, 201, 30))
        self.pushButton_a3C.setObjectName("pushButton_a3C")
        self.pushButton_a6C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a6C.setGeometry(QtCore.QRect(1208, 364, 201, 30))
        self.pushButton_a6C.setObjectName("pushButton_a6C")
        self.pushButton_3C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3C.setGeometry(QtCore.QRect(1000, 244, 141, 30))
        self.pushButton_3C.setObjectName("pushButton_3C")
        self.pushButton_6C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6C.setGeometry(QtCore.QRect(1000, 364, 201, 30))
        self.pushButton_6C.setObjectName("pushButton_6C")
        self.pushButton_a4C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a4C.setGeometry(QtCore.QRect(1208, 284, 201, 30))
        self.pushButton_a4C.setObjectName("pushButton_a4C")
        self.pushButton_a5C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a5C.setGeometry(QtCore.QRect(1208, 324, 201, 30))
        self.pushButton_a5C.setObjectName("pushButton_a5C")
        self.pushButton_4C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4C.setGeometry(QtCore.QRect(1000, 284, 141, 30))
        self.pushButton_4C.setObjectName("pushButton_4C")
        self.pushButton_a7C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a7C.setGeometry(QtCore.QRect(1208, 404, 201, 30))
        self.pushButton_a7C.setObjectName("pushButton_a7C")
        self.pushButton_a2C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_a2C.setGeometry(QtCore.QRect(1208, 204, 201, 30))
        self.pushButton_a2C.setObjectName("pushButton_a2C")
        self.pushButton_2C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2C.setGeometry(QtCore.QRect(1000, 204, 201, 30))
        self.pushButton_2C.setObjectName("pushButton_2C")
        self.pushButton_1C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1C.setGeometry(QtCore.QRect(1000, 164, 200, 30))
        self.pushButton_1C.setObjectName("pushButton_1C")
        self.frame_qr = QtWidgets.QFrame(self.centralwidget)
        self.frame_qr.setGeometry(QtCore.QRect(30, 630, 1371, 181))
        self.frame_qr.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_qr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_qr.setObjectName("frame_qr")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 460, 1371, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.label_A.raise_()
        self.spin_1A.raise_()
        self.spin_2A.raise_()
        self.label_xA.raise_()
        self.pushButton_PR1A.raise_()
        self.pushButton_CL1A.raise_()
        self.gridLayoutWidget_2.raise_()
        self.label_rA.raise_()
        self.verticalLayoutWidget.raise_()
        self.spin_2B.raise_()
        self.label_B.raise_()
        self.label_xA_2.raise_()
        self.pushButton_PR1B.raise_()
        self.label_rB.raise_()
        self.gridLayoutWidget_4.raise_()
        self.pushButton_CL1B.raise_()
        self.spin_1B.raise_()
        self.label_xA_3.raise_()
        self.spin_2C.raise_()
        self.label_C.raise_()
        self.label_rC.raise_()
        self.pushButton_PR1C.raise_()
        self.gridLayoutWidget_5.raise_()
        self.pushButton_CL1C.raise_()
        self.spin_1C.raise_()
        self.label_rav.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.spin_p1A.raise_()
        self.spin_p3A.raise_()
        self.spin_p2A.raise_()
        self.spin_p1B.raise_()
        self.spin_p3B.raise_()
        self.spin_p2B.raise_()
        self.spin_p1C.raise_()
        self.spin_p2C.raise_()
        self.spin_p3C.raise_()
        self.pushButton_a1A.raise_()
        self.pushButton_5A.raise_()
        self.pushButton_7A.raise_()
        self.pushButton_a3A.raise_()
        self.pushButton_a6A.raise_()
        self.pushButton_3A.raise_()
        self.pushButton_6A.raise_()
        self.pushButton_a4A.raise_()
        self.pushButton_a5A.raise_()
        self.pushButton_4A.raise_()
        self.pushButton_a7A.raise_()
        self.pushButton_a2A.raise_()
        self.pushButton_2A.raise_()
        self.pushButton_1A.raise_()
        self.pushButton_a1B.raise_()
        self.pushButton_5B.raise_()
        self.pushButton_7B.raise_()
        self.pushButton_a3B.raise_()
        self.pushButton_a6B.raise_()
        self.pushButton_3B.raise_()
        self.pushButton_6B.raise_()
        self.pushButton_a4B.raise_()
        self.pushButton_a5B.raise_()
        self.pushButton_4B.raise_()
        self.pushButton_a7B.raise_()
        self.pushButton_a2B.raise_()
        self.pushButton_2B.raise_()
        self.pushButton_1B.raise_()
        self.pushButton_a1C.raise_()
        self.pushButton_5C.raise_()
        self.pushButton_7C.raise_()
        self.pushButton_a3C.raise_()
        self.pushButton_a6C.raise_()
        self.pushButton_3C.raise_()
        self.pushButton_6C.raise_()
        self.pushButton_a4C.raise_()
        self.pushButton_a5C.raise_()
        self.pushButton_4C.raise_()
        self.pushButton_a7C.raise_()
        self.pushButton_a2C.raise_()
        self.pushButton_2C.raise_()
        self.pushButton_1C.raise_()
        self.frame_qr.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        a = ['A', 'B', 'C']
        for i in a:
            for j in range(1, 3):
                getattr(self, 'spin_%s%s' % (j, i)).setValue(5)
        for k in a:
            for i in range(1, 6):
                for j in range(1, 6):
                    getattr(self, 'spin_%s%s%s' % (i, j, k)).setMinimum(-99999)
        for i in a:
            if i == 'A':
                self.pushButton_PR1A.clicked.connect(lambda: self.size_change('A'))
                self.pushButton_CL1A.clicked.connect(lambda: self.clear('A'))
                self.pushButton_a1A.clicked.connect(lambda: self.transposition('A'))
                self.pushButton_a2A.clicked.connect(lambda: self.rank('A'))
                self.pushButton_a3A.clicked.connect(lambda: self.null_matrix('A'))
                self.pushButton_a4A.clicked.connect(lambda: self.diagonal_matrix('A'))
                self.pushButton_a5A.clicked.connect(lambda: self.identity_matrix('A'))
                self.pushButton_a6A.clicked.connect(lambda: self.lower_matrix('A'))
                self.pushButton_a7A.clicked.connect(lambda: self.choleskiy('A'))
                self.pushButton_1A.clicked.connect(lambda: self.determinant('A'))
                self.pushButton_2A.clicked.connect(lambda: self.inverse_matrix('A'))
                self.pushButton_3A.clicked.connect(lambda: self.multiplication('A'))
                self.pushButton_4A.clicked.connect(lambda: self.pow('A'))
                self.pushButton_5A.clicked.connect(lambda: self.addition('A'))
                self.pushButton_6A.clicked.connect(lambda: self.upper_matrix('A'))
                self.pushButton_7A.clicked.connect(lambda: self.qr('A'))
            elif i == 'B':
                self.pushButton_PR1B.clicked.connect(lambda: self.size_change('B'))
                self.pushButton_CL1B.clicked.connect(lambda: self.clear('B'))
                self.pushButton_a1B.clicked.connect(lambda: self.transposition('B'))
                self.pushButton_a2B.clicked.connect(lambda: self.rank('B'))
                self.pushButton_a3B.clicked.connect(lambda: self.null_matrix('B'))
                self.pushButton_a4B.clicked.connect(lambda: self.diagonal_matrix('B'))
                self.pushButton_a5B.clicked.connect(lambda: self.identity_matrix('B'))
                self.pushButton_a6B.clicked.connect(lambda: self.lower_matrix('B'))
                self.pushButton_a7B.clicked.connect(lambda: self.choleskiy('B'))
                self.pushButton_1B.clicked.connect(lambda: self.determinant('B'))
                self.pushButton_2B.clicked.connect(lambda: self.inverse_matrix('B'))
                self.pushButton_3B.clicked.connect(lambda: self.multiplication('B'))
                self.pushButton_4B.clicked.connect(lambda: self.pow('B'))
                self.pushButton_5B.clicked.connect(lambda: self.addition('B'))
                self.pushButton_6B.clicked.connect(lambda: self.upper_matrix('B'))
                self.pushButton_7B.clicked.connect(lambda: self.qr('B'))
            elif i == 'C':
                self.pushButton_PR1C.clicked.connect(lambda: self.size_change('C'))
                self.pushButton_CL1C.clicked.connect(lambda: self.clear('C'))
                self.pushButton_a1C.clicked.connect(lambda: self.transposition('C'))
                self.pushButton_a2C.clicked.connect(lambda: self.rank('C'))
                self.pushButton_a3C.clicked.connect(lambda: self.null_matrix('C'))
                self.pushButton_a4C.clicked.connect(lambda: self.diagonal_matrix('C'))
                self.pushButton_a5C.clicked.connect(lambda: self.identity_matrix('C'))
                self.pushButton_a6C.clicked.connect(lambda: self.lower_matrix('C'))
                self.pushButton_a7C.clicked.connect(lambda: self.choleskiy('C'))
                self.pushButton_1C.clicked.connect(lambda: self.determinant('C'))
                self.pushButton_2C.clicked.connect(lambda: self.inverse_matrix('C'))
                self.pushButton_3C.clicked.connect(lambda: self.multiplication('C'))
                self.pushButton_4C.clicked.connect(lambda: self.pow('C'))
                self.pushButton_5C.clicked.connect(lambda: self.addition('C'))
                self.pushButton_6C.clicked.connect(lambda: self.upper_matrix('C'))
                self.pushButton_7C.clicked.connect(lambda: self.qr('C'))
        self.pushButton_s0.clicked.connect(self.swap)
        self.pushButton_s3.clicked.connect(self.matrix_mult)
        b = ['add', 'dif']
        for operation in b:
            if operation == 'add':
                self.pushButton_s1.clicked.connect(lambda: self.add_dif('add'))
            elif operation == 'dif':
                self.pushButton_s2.clicked.connect(lambda: self.add_dif('dif'))
        qr = ['q', 'r']
        for k in qr:
            for i in range(1, 6):
                for j in range(1, 6):
                    getattr(self, 'label_%s%s%s' % (i, j, k)).hide()
        self.label_r.hide()
        self.label_q.hide()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_A.setText(_translate("MainWindow", "Матрица А"))
        self.label_xA.setText(_translate("MainWindow", "х"))
        self.pushButton_PR1A.setText(_translate("MainWindow", "Принять"))
        self.pushButton_CL1A.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_s0.setText(_translate("MainWindow", "<-->"))
        self.pushButton_s1.setText(_translate("MainWindow", "A + B"))
        self.pushButton_s2.setText(_translate("MainWindow", "A - B"))
        self.pushButton_s3.setText(_translate("MainWindow", "A x B"))
        self.label_B.setText(_translate("MainWindow", "Матрица B"))
        self.label_xA_2.setText(_translate("MainWindow", "х"))
        self.pushButton_PR1B.setText(_translate("MainWindow", "Принять"))
        self.pushButton_CL1B.setText(_translate("MainWindow", "Очистить"))
        self.label_xA_3.setText(_translate("MainWindow", "х"))
        self.label_C.setText(_translate("MainWindow", "Матрица C"))
        self.pushButton_PR1C.setText(_translate("MainWindow", "Принять"))
        self.pushButton_CL1C.setText(_translate("MainWindow", "Очистить"))
        self.label_rav.setText(_translate("MainWindow", "="))
        self.label_q.setText(_translate("MainWindow", "A = Q x R, где Q = "))
        self.label_54q.setText(_translate("MainWindow", "0"))
        self.label_31q.setText(_translate("MainWindow", "0"))
        self.label_34q.setText(_translate("MainWindow", "0"))
        self.label_52q.setText(_translate("MainWindow", "0"))
        self.label_14q.setText(_translate("MainWindow", "0"))
        self.label_44q.setText(_translate("MainWindow", "0"))
        self.label_32q.setText(_translate("MainWindow", "0"))
        self.label_51q.setText(_translate("MainWindow", "0"))
        self.label_21q.setText(_translate("MainWindow", "0"))
        self.label_33q.setText(_translate("MainWindow", "0"))
        self.label_42q.setText(_translate("MainWindow", "0"))
        self.label_12q.setText(_translate("MainWindow", "0"))
        self.label_22q.setText(_translate("MainWindow", "0"))
        self.label_11q.setText(_translate("MainWindow", "0"))
        self.label_53q.setText(_translate("MainWindow", "0"))
        self.label_41q.setText(_translate("MainWindow", "0"))
        self.label_24q.setText(_translate("MainWindow", "0"))
        self.label_25q.setText(_translate("MainWindow", "0"))
        self.label_13q.setText(_translate("MainWindow", "0"))
        self.label_43q.setText(_translate("MainWindow", "0"))
        self.label_35q.setText(_translate("MainWindow", "0"))
        self.label_45q.setText(_translate("MainWindow", "0"))
        self.label_15q.setText(_translate("MainWindow", "0"))
        self.label_55q.setText(_translate("MainWindow", "0"))
        self.label_23q.setText(_translate("MainWindow", "0"))
        self.label_r.setText(_translate("MainWindow", "R = "))
        self.label_53r.setText(_translate("MainWindow", "0"))
        self.label_12r.setText(_translate("MainWindow", "0"))
        self.label_41r.setText(_translate("MainWindow", "0"))
        self.label_25r.setText(_translate("MainWindow", "0"))
        self.label_31r.setText(_translate("MainWindow", "0"))
        self.label_34r.setText(_translate("MainWindow", "0"))
        self.label_22r.setText(_translate("MainWindow", "0"))
        self.label_24r.setText(_translate("MainWindow", "0"))
        self.label_35r.setText(_translate("MainWindow", "0"))
        self.label_52r.setText(_translate("MainWindow", "0"))
        self.label_33r.setText(_translate("MainWindow", "0"))
        self.label_51r.setText(_translate("MainWindow", "0"))
        self.label_43r.setText(_translate("MainWindow", "0"))
        self.label_11r.setText(_translate("MainWindow", "0"))
        self.label_44r.setText(_translate("MainWindow", "0"))
        self.label_15r.setText(_translate("MainWindow", "0"))
        self.label_54r.setText(_translate("MainWindow", "0"))
        self.label_55r.setText(_translate("MainWindow", "0"))
        self.label_45r.setText(_translate("MainWindow", "0"))
        self.label_32r.setText(_translate("MainWindow", "0"))
        self.label_21r.setText(_translate("MainWindow", "0"))
        self.label_13r.setText(_translate("MainWindow", "0"))
        self.label_23r.setText(_translate("MainWindow", "0"))
        self.label_42r.setText(_translate("MainWindow", "0"))
        self.label_14r.setText(_translate("MainWindow", "0"))
        self.pushButton_a1A.setText(_translate("MainWindow", "Транспорнировать"))
        self.pushButton_5A.setText(_translate("MainWindow", "Увеличить на"))
        self.pushButton_7A.setText(_translate("MainWindow", "QR - разложение"))
        self.pushButton_a3A.setText(_translate("MainWindow", "Нулевая матрица"))
        self.pushButton_a6A.setText(_translate("MainWindow", "Нижн. треуг. матрица"))
        self.pushButton_3A.setText(_translate("MainWindow", "Умножить на"))
        self.pushButton_6A.setText(_translate("MainWindow", "Верх. треуг. матрица"))
        self.pushButton_a4A.setText(_translate("MainWindow", "Диагональная"))
        self.pushButton_a5A.setText(_translate("MainWindow", "Единичная"))
        self.pushButton_4A.setText(_translate("MainWindow", "Степень"))
        self.pushButton_a7A.setText(_translate("MainWindow", "Разл. Холецкого"))
        self.pushButton_a2A.setText(_translate("MainWindow", "Ранг"))
        self.pushButton_2A.setText(_translate("MainWindow", "Обратная"))
        self.pushButton_1A.setText(_translate("MainWindow", "Определитель"))
        self.pushButton_a1B.setText(_translate("MainWindow", "Транспорнировать"))
        self.pushButton_5B.setText(_translate("MainWindow", "Увеличить на"))
        self.pushButton_7B.setText(_translate("MainWindow", "QR - разложение"))
        self.pushButton_a3B.setText(_translate("MainWindow", "Нулевая матрица"))
        self.pushButton_a6B.setText(_translate("MainWindow", "Нижн. треуг. матрица"))
        self.pushButton_3B.setText(_translate("MainWindow", "Умножить на"))
        self.pushButton_6B.setText(_translate("MainWindow", "Верх. треуг. матрица"))
        self.pushButton_a4B.setText(_translate("MainWindow", "Диагональная"))
        self.pushButton_a5B.setText(_translate("MainWindow", "Единичная"))
        self.pushButton_4B.setText(_translate("MainWindow", "Степень"))
        self.pushButton_a7B.setText(_translate("MainWindow", "Разл. Холецкого"))
        self.pushButton_a2B.setText(_translate("MainWindow", "Ранг"))
        self.pushButton_2B.setText(_translate("MainWindow", "Обратная"))
        self.pushButton_1B.setText(_translate("MainWindow", "Определитель"))
        self.pushButton_a1C.setText(_translate("MainWindow", "Транспорнировать"))
        self.pushButton_5C.setText(_translate("MainWindow", "Увеличить на"))
        self.pushButton_7C.setText(_translate("MainWindow", "QR - разложение"))
        self.pushButton_a3C.setText(_translate("MainWindow", "Нулевая матрица"))
        self.pushButton_a6C.setText(_translate("MainWindow", "Нижн. треуг. матрица"))
        self.pushButton_3C.setText(_translate("MainWindow", "Умножить на"))
        self.pushButton_6C.setText(_translate("MainWindow", "Верх. треуг. матрица"))
        self.pushButton_a4C.setText(_translate("MainWindow", "Диагональная"))
        self.pushButton_a5C.setText(_translate("MainWindow", "Единичная"))
        self.pushButton_4C.setText(_translate("MainWindow", "Степень"))
        self.pushButton_a7C.setText(_translate("MainWindow", "Разл. Холецкого"))
        self.pushButton_a2C.setText(_translate("MainWindow", "Ранг"))
        self.pushButton_2C.setText(_translate("MainWindow", "Обратная"))
        self.pushButton_1C.setText(_translate("MainWindow", "Определитель"))
